/*
Note: this file is generated by Chatgpt
This task reads the real BRAMs through their read ports.

The valid bits are stored outside the BRAM, so they are used to decide
which BRAM entries are active and should be printed.
*/

task automatic print_tables();

    logic [143:0] order_entry;
    logic [95:0]  level_entry;

    // Wait until order_store and order_level are both idle.
    // The testbench can safely use their BRAM read ports now.
    wait (
        dut.parser_event_ready == 1'b1 &&
        dut.level_update_ready == 1'b1
    );

    @(negedge clk);


    // ---------------------------------------------------------
    // Read the real order-store BRAMs
    // ---------------------------------------------------------
    $display("\nORDER STORE BRAM");
    $display("+------+-------+----------------------+--------+------+------------+------------+");
    $display("| Bank | Addr  | Order ID             | Symbol | Side | Price      | Quantity   |");
    $display("+------+-------+----------------------+--------+------+------------+------------+");

    // All three banks share the same read address.
    force dut.order_store_read_en = 3'b111;

    for (int addr = 0; addr < 128; addr++) begin

        force dut.order_store_read_addr = addr;

        // BRAM accepts the address on this rising edge.
        @(posedge clk);

        // Read data is stable by the following falling edge.
        @(negedge clk);

        for (int bank = 0; bank < 3; bank++) begin

            // Only print active entries.
            // Invalid BRAM locations may still contain old data.
            if (dut.u_order_store.valid_bits[bank][addr] === 1'b1) begin

                order_entry = dut.order_store_read_data[bank];

                $display(
                    "| %4d | %5d | %20d | %6d | %4s | %10d | %10d |",
                    bank,
                    addr,
                    order_entry[143:80],
                    order_entry[79:72],
                    order_entry[71] ? "SELL" : "BUY ",
                    order_entry[70:39],
                    order_entry[38:7]
                );

            end
        end
    end

    release dut.order_store_read_addr;
    release dut.order_store_read_en;

    $display("+------+-------+----------------------+--------+------+------------+------------+");


    // ---------------------------------------------------------
    // Read the real order-level BRAM
    // ---------------------------------------------------------
    $display("\nORDER LEVEL BRAM");
    $display("+-------+--------+------+------------+----------------+-------------+");
    $display("| Addr  | Symbol | Side | Price      | Total Quantity | Order Count |");
    $display("+-------+--------+------+------------+----------------+-------------+");

    force dut.order_level_read_en = 1'b1;

    for (int addr = 0; addr < 128; addr++) begin

        force dut.order_level_read_addr = addr;

        // BRAM accepts the address on this rising edge.
        @(posedge clk);

        // Read data is stable by the following falling edge.
        @(negedge clk);

        if (dut.u_order_level.level_valid_bits_bram[addr] === 1'b1) begin

            level_entry = dut.order_level_read_data;

            $display(
                "| %5d | %6d | %4s | %10d | %14d | %11d |",
                addr,
                level_entry[95:88],
                level_entry[87] ? "SELL" : "BUY ",
                level_entry[86:55],
                level_entry[54:23],
                level_entry[22:7]
            );

        end
    end

    release dut.order_level_read_addr;
    release dut.order_level_read_en;

    $display("+-------+--------+------+------------+----------------+-------------+");

endtask