/*
Note: this file is generated by Chatgpt
This task reads the real BRAMs through their read ports.

The valid bits are stored outside the BRAM, so they are used to decide
which BRAM entries are active and should be printed.
*/

// Static testbench signal used to scan BRAM addresses.
// It must be outside the automatic task because Vivado does not allow
// an automatic variable on the right side of a force statement.
logic [6:0] bram_scan_addr = '0;


task automatic print_tables();

    logic [143:0] order_entry;
    logic [95:0]  level_entry;


    // Wait until order_store and order_level are idle.
    // It is now safe for the testbench to use the BRAM read ports.
    wait (
        dut.parser_event_ready == 1'b1 &&
        dut.level_update_ready == 1'b1
    );

    @(negedge clk);


    // ---------------------------------------------------------
    // Read the real order-store BRAMs
    // ---------------------------------------------------------
    $display("\nORDER STORE BRAM");
    $display("+------+-------+----------------------+--------+------+------------+------------+");
    $display("| Bank | Addr  | Order ID             | Symbol | Side | Price      | Quantity   |");
    $display("+------+-------+----------------------+--------+------+------------+------------+");


    // Take control of the read ports of all three order-store BRAMs.
    force dut.u_order_store_bram_0.enb = 1'b1;
    force dut.u_order_store_bram_1.enb = 1'b1;
    force dut.u_order_store_bram_2.enb = 1'b1;

    force dut.u_order_store_bram_0.addrb = bram_scan_addr;
    force dut.u_order_store_bram_1.addrb = bram_scan_addr;
    force dut.u_order_store_bram_2.addrb = bram_scan_addr;


    for (int addr = 0; addr < 128; addr++) begin

        bram_scan_addr = addr[6:0];

        // BRAM accepts the address on the rising edge.
        @(posedge clk);

        // Read output is stable by the falling edge.
        @(negedge clk);


        for (int bank = 0; bank < 3; bank++) begin

            // Invalid locations can contain old data, so only print
            // locations whose separate valid bit is set.
            if (dut.u_order_store.valid_bits[bank][bram_scan_addr] === 1'b1) begin

                order_entry = dut.order_store_read_data[bank];

                $display(
                    "| %4d | %5d | %20d | %6d | %4s | %10d | %10d |",
                    bank,
                    bram_scan_addr,
                    order_entry[143:80],
                    order_entry[79:72],
                    order_entry[71] ? "SELL" : "BUY ",
                    order_entry[70:39],
                    order_entry[38:7]
                );

            end
        end
    end


    // Return control of the BRAM ports to order_store.
    release dut.u_order_store_bram_0.addrb;
    release dut.u_order_store_bram_1.addrb;
    release dut.u_order_store_bram_2.addrb;

    release dut.u_order_store_bram_0.enb;
    release dut.u_order_store_bram_1.enb;
    release dut.u_order_store_bram_2.enb;


    $display("+------+-------+----------------------+--------+------+------------+------------+");


    // ---------------------------------------------------------
    // Read the real order-level BRAM
    // ---------------------------------------------------------
    $display("\nORDER LEVEL BRAM");
    $display("+-------+--------+------+------------+----------------+-------------+");
    $display("| Addr  | Symbol | Side | Price      | Total Quantity | Order Count |");
    $display("+-------+--------+------+------------+----------------+-------------+");


    // Take control of the order-level BRAM read port.
    force dut.u_order_level_bram.enb = 1'b1;
    force dut.u_order_level_bram.addrb = bram_scan_addr;


    for (int addr = 0; addr < 128; addr++) begin

        bram_scan_addr = addr[6:0];

        // BRAM accepts the address on the rising edge.
        @(posedge clk);

        // Read output is stable by the falling edge.
        @(negedge clk);


        if (dut.u_order_level.level_valid_bits_bram[bram_scan_addr] === 1'b1) begin

            level_entry = dut.order_level_read_data;

            $display(
                "| %5d | %6d | %4s | %10d | %14d | %11d |",
                bram_scan_addr,
                level_entry[95:88],
                level_entry[87] ? "SELL" : "BUY ",
                level_entry[86:55],
                level_entry[54:23],
                level_entry[22:7]
            );

        end
    end


    // Return control of the BRAM port to order_level.
    release dut.u_order_level_bram.addrb;
    release dut.u_order_level_bram.enb;


    $display("+-------+--------+------+------------+----------------+-------------+");

endtask